package vault

// battles.env: the CLI's configuration file. It holds a private key, so it is
// written 0600 and git-ignored. Every key is also honored as an environment
// variable of the same name, so a CI job can run without the file.

import (
	"crypto/ecdsa"
	"errors"
	"fmt"
	"io/fs"
	"math/big"
	"os"
	"strconv"
	"strings"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/joho/godotenv"
)

const (
	ConfigFileName = "battles.env"

	EnvEndpoint   = "BATTLES_ETH_ENDPOINT"
	EnvPrivateKey = "BATTLES_PRIVATE_KEY"
	EnvVaultAddr  = "BATTLES_VAULT_ADDR"
	EnvChainID    = "BATTLES_CHAIN_ID"
	EnvVaultBlock = "BATTLES_VAULT_BLOCK"

	configFileMode = 0o600
)

var errNotImplemented = errors.New("not implemented")

// Config is everything the CLI needs to talk to one Vault.
type Config struct {
	EthEndpoint string
	PrivateKey  string // hex, 0x optional
	VaultAddr   common.Address
	ChainID     *big.Int
	// VaultBlock is the block the Vault was deployed in: where event scans
	// start. Zero means unknown; the session then finds it by binary search.
	VaultBlock uint64
}

// LoadConfig reads path, then lets same-named environment variables override
// each value. With no file, the environment alone is used; when that is empty
// too, the error wraps fs.ErrNotExist so the caller can start the wizard.
func LoadConfig(path string) (*Config, error) {
	values, readErr := godotenv.Read(path)
	if readErr != nil && !errors.Is(readErr, fs.ErrNotExist) {
		return nil, fmt.Errorf("failed to read %s: %w", path, readErr)
	}
	get := func(name string) string {
		if v, ok := os.LookupEnv(name); ok && v != "" {
			return v
		}
		return values[name]
	}
	if readErr != nil && get(EnvEndpoint) == "" && get(EnvPrivateKey) == "" && get(EnvVaultAddr) == "" {
		return nil, fmt.Errorf("no %s and no %s in the environment: %w", path, EnvEndpoint, readErr)
	}
	cfg := &Config{EthEndpoint: get(EnvEndpoint), PrivateKey: get(EnvPrivateKey)}
	if v := get(EnvVaultAddr); v != "" {
		if !common.IsHexAddress(v) {
			return nil, fmt.Errorf("%s is not an address: %q", EnvVaultAddr, v)
		}
		cfg.VaultAddr = common.HexToAddress(v)
	}
	if v := get(EnvChainID); v != "" {
		id, ok := new(big.Int).SetString(v, 10)
		if !ok {
			return nil, fmt.Errorf("%s is not a number: %q", EnvChainID, v)
		}
		cfg.ChainID = id
	}
	if v := get(EnvVaultBlock); v != "" {
		n, err := strconv.ParseUint(v, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("%s is not a block number: %q", EnvVaultBlock, v)
		}
		cfg.VaultBlock = n
	}
	return cfg, nil
}

// Save writes the config to path with mode 0600.
func (c *Config) Save(path string) error {
	chain := ""
	if c.ChainID != nil {
		chain = c.ChainID.String()
	}
	body := strings.Join([]string{
		"# battles CLI configuration. Generated by `battles init`; holds a private key, keep it private.",
		EnvEndpoint + "=" + c.EthEndpoint,
		EnvPrivateKey + "=" + c.PrivateKey,
		EnvVaultAddr + "=" + c.VaultAddr.Hex(),
		EnvChainID + "=" + chain,
		EnvVaultBlock + "=" + strconv.FormatUint(c.VaultBlock, 10),
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(body), configFileMode); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}
	// WriteFile only applies the mode to a new file; enforce it on rewrites.
	return os.Chmod(path, configFileMode)
}

// Validate checks that every field the CLI needs is present and well-formed.
func (c *Config) Validate() error {
	if c.EthEndpoint == "" {
		return fmt.Errorf("%s is not set", EnvEndpoint)
	}
	if _, _, err := c.Signer(); err != nil {
		return err
	}
	if c.VaultAddr == (common.Address{}) {
		return fmt.Errorf("%s is not set (run `battles init`, or `battles deploy`)", EnvVaultAddr)
	}
	if c.ChainID == nil || c.ChainID.Sign() <= 0 {
		return fmt.Errorf("%s is not set", EnvChainID)
	}
	return nil
}

// Signer parses the private key and returns it with its address.
func (c *Config) Signer() (*ecdsa.PrivateKey, common.Address, error) {
	if c.PrivateKey == "" {
		return nil, common.Address{}, fmt.Errorf("%s is not set", EnvPrivateKey)
	}
	key, err := crypto.HexToECDSA(strings.TrimPrefix(strings.TrimSpace(c.PrivateKey), "0x"))
	if err != nil {
		return nil, common.Address{}, fmt.Errorf("%s is not a valid private key: %w", EnvPrivateKey, err)
	}
	return key, crypto.PubkeyToAddress(key.PublicKey), nil
}
